controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use app\models\ContactForm;
use app\models\search\ToursOuterSearch;
use app\models\search\ToursFavoritesSearch;

class SiteController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {
        $searchModel = new ToursOuterSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = Yii::$app->userHelper->getLoginForm();
        if ($model->load(Yii::$app->request->post()) and Yii::$app->userHelper->login($model)) {
            return $this->goBack();
        }

        $model->password = '';
        Yii::$app->viewManager->setBodyClass('login-block');
        return $this->render('login', [
                    'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact() {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
                    'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout() {
        return $this->render('about');
    }

    public function actionRegister() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = Yii::$app->userHelper->getUserRegisterForm();
        if ($model->load(Yii::$app->request->post())and $model->validate() and Yii::$app->userHelper->createNew($model)) {
            Yii::$app->userHelper->login($model);
            return $this->goHome();
        }
        return $this->render('register', ['model' => $model]);
    }

    public function actionFavorites() {
        $searchModel = new ToursFavoritesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('favorites', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider
        ]);
    }

    public function actionToggleFavorite($id) {
        Yii::$app->tourHelper->toggleFavorite($id);
    }

}

views/site/_template.php
<div class="announcement tour">
    <div class="tour__name">
        <span>Название: <?= $model->name ?></span>
        <span><?= $model->is_included_meal ? 'Включено питание' : '' ?></span>
    </div>
    <div class="tour__price">
        <span>Цена: <?= $model->price ?></span>
        <span><?= $model->is_travel_included ? 'Включен проезд' : '' ?></span>
    </div>
    <div class="tour__city">Город: <?= $model->city->name ?></div>
    <div class="tour__type">Тип: <?= $model->tourType->name ?></div>
    <div class="tour__night">Количество ночей: <?= $model->night_count ?></div>
    <div class="tour_button add_favorite" data-id="<?= $model->id ?>" onclick="toggle_favorite(event)"><?= Yii::$app->tourHelper->isFavorite($model->id) ? 'Удалить' : 'В избранное' ?></div>
</div>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/favorites.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use yii\widgets\Pjax;
use yii\widgets\ActiveForm;
?>



<header class="header">
    <?php
    $form = ActiveForm::begin([
                'action' => ['/site/index'],
                'method' => 'get',
                'options' => [
                    'data-pjax' => 1
                ],
    ]);
    ?>    

    <div class="form-wrapper">
        <?= $form->field(new \app\models\search\ToursOuterSearch(), 'name')->textInput(['class' => 'form-search-el', 'placeholder' => "Поиск"])->label(false) ?>
        <button class="icon-button" type="submit"><i class="fas fa-search"></i></button>
    </div>
    <?php ActiveForm::end() ?>
    <?php if (!Yii::$app->user->isGuest): ?>
        <nav class="buttons-authorized-block">
            <?= Html::a('Главная', ['/site/index'], ['class' => 'button text-center']) ?>
            <?= Html::a('Выход', ['/site/logout'], ['class' => 'button text-center']) ?>
        </nav>
    <?php endif; ?>
    <nav class="button-guest-block <?= Yii::$app->user->isGuest ? null : 'grid-none' ?>">
        <?php if (Yii::$app->user->isGuest): ?>
            <?= Html::a('Вход', ['/site/login'], ['class' => 'button text-center']) ?>
            <?= Html::a('Регистрация', ['/site/register'], ['class' => 'button text-center']) ?>
        <?php endif; ?>
    </nav>
</header>

<?php Pjax::begin(['id' => 'favorites']) ?>
<section class="tours">
    <?= ListView::widget(['dataProvider' => $dataProvider, 'itemView' => '_template']) ?>
</section>
<?php Pjax::end() ?>
<script>
    function toggle_favorite(event) {
        event.preventDefault();
        $.ajax({
            url: '/site/toggle-favorite',
            data: {id: event.target.dataset.id},
            success: function (data, textStatus, jqXHR) {
                $.pjax.reload({container: '#favorites'});
            }
        });
    }
</script>

views/site/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use yii\widgets\Pjax;
use yii\widgets\ActiveForm;
?>


<?php
$form = ActiveForm::begin([
            'action' => ['index'],
            'method' => 'get',
            'options' => [
                'data-pjax' => 1
            ],
        ]);
?>

<header class="header">
    <div class="form-wrapper">
        <?= $form->field($searchModel, 'name')->textInput(['class' => 'form-search-el', 'placeholder' => "Поиск"])->label(false) ?>
        <button class="icon-button" type="submit"><i class="fas fa-search"></i></button>
    </div>
    <?php if (!Yii::$app->user->isGuest): ?>
        <nav class="buttons-authorized-block">
            <?= Html::a('Избранное', ['/site/favorites'], ['class' => 'button text-center']) ?>
            <?= Html::a('Выход', ['/site/logout'], ['class' => 'button text-center']) ?>
        </nav>
    <?php endif; ?>
    <nav class="button-guest-block <?= Yii::$app->user->isGuest ? null : 'grid-none' ?>">
        <?php if (Yii::$app->user->isGuest): ?>
            <?= Html::a('Вход', ['/site/login'], ['class' => 'button text-center']) ?>
            <?= Html::a('Регистрация', ['/site/register'], ['class' => 'button text-center']) ?>
        <?php endif; ?>
    </nav>
</header>

<section class="ads">

    <a class="announcement" <?= !Yii::$app->user->isGuest ? 'style="margin-top: -60px;"' : '' ?>>

        <div class="main-inf">
            <div>
                <div class="form-hint">Страна</div>
                <?= $form->field($searchModel, 'city_id')->dropDownList(Yii::$app->citiesHelper->getList(), ['class' => 'information-field', 'onchange' => 'submit()'])->label(false) ?></div>
            <div>
                <div class="form-hint">Тип тура</div>
                <?= $form->field($searchModel, 'tour_type_id')->dropDownList(Yii::$app->tourTypesHelper->getList(), ['class' => 'information-field', 'onchange' => 'submit()'])->label(false) ?></div>
            <div>
                <div class="form-hint">Максимальная цена</div>
                <?= $form->field($searchModel, 'price')->textInput(['class' => 'information-field', 'onchange' => 'submit()'])->label(false) ?></div>
            <div>
                <div class="form-hint">Количество ночей</div>
                <?= $form->field($searchModel, 'night_count')->textInput(['class' => 'information-field', 'onchange' => 'submit()'])->label(false) ?></div>

        </div>

        <div class="add-inf">

            <div class="center">
                <?= $form->field($searchModel, 'is_included_meal')->checkbox(['class' => 'information-field', 'label' => null, 'onchange' => 'submit()']) ?>
                <span>Питание включено в стоимость</span>
            </div>

            <div class="center">
                <?= $form->field($searchModel, 'is_travel_included')->checkbox(['class' => 'information-field', 'onchange' => 'submit()', 'label' => null]) ?>
                <span>Проезд включен в стоимость</span>
            </div>
        </div>



    </a>
</section>

<?php ActiveForm::end(); ?>

<?php Pjax::begin(['id' => 'tours']) ?>
<section class="tours">
    <?= ListView::widget(['dataProvider' => $dataProvider, 'itemView' => '_template']) ?>
</section>
<?php Pjax::end() ?>
<script>
    function toggle_favorite(event) {
        event.preventDefault();
        $.ajax({
            url: '/site/toggle-favorite',
            data: {id: event.target.dataset.id},
            success: function (data, textStatus, jqXHR) {
                $.pjax.reload({container: '#tours'});
            }
        });
    }
</script>

views/site/login.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-login">
    <?php
    $form = ActiveForm::begin();
    ?>
    <section class="login pd-25px">
        <p class="login-head">Вход</p>


        <?= $form->field($model, 'email_address', ['options' => ['class' => 'w-100 mt-15px']])->textInput(['autofocus' => true, 'class' => 'login-form-el', 'placeholder' => 'Email адресс'])->label(false) ?>


        <?= $form->field($model, 'password', ['options' => ['class' => 'w-100 mt-15px']])->passwordInput(['class' => 'login-form-el', 'placeholder' => 'Пароль'])->label(false) ?>


        <?= Html::submitButton('Войти', ['class' => 'button w-100 mt-15px']) ?>
        <?= Html::a('Зарегистрироваться', ['site/register'], ['class' => 'w-100 mt-15px text-center']) ?>

        <?php ActiveForm::end(); ?>
    </section>

</div>

views/site/register.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Register';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <?php
    $form = ActiveForm::begin();
    ?>
    <section class="login pd-25px">
        <p class="login-head">Регистрация</p>

        <?= $form->field($model, 'name', ['options' => ['class' => 'w-100 mt-15px']])->textInput(['autofocus' => true, 'class' => 'login-form-el', 'placeholder' => 'Имя'])->label(false) ?>

        <?= $form->field($model, 'surname', ['options' => ['class' => 'w-100 mt-15px']])->textInput(['autofocus' => true, 'class' => 'login-form-el', 'placeholder' => 'Фамилия'])->label(false) ?>

        <?= $form->field($model, 'email_address', ['options' => ['class' => 'w-100 mt-15px']])->textInput(['autofocus' => true, 'class' => 'login-form-el', 'placeholder' => 'Email адресс'])->label(false) ?>


        <?= $form->field($model, 'password', ['options' => ['class' => 'w-100 mt-15px']])->passwordInput(['class' => 'login-form-el', 'placeholder' => 'Пароль'])->label(false) ?>

        <?= $form->field($model, 'confirm_password', ['options' => ['class' => 'w-100 mt-15px']])->passwordInput(['class' => 'login-form-el', 'placeholder' => 'Повторите пароль'])->label(false) ?>


        <?= Html::submitButton('Зарегистрироваться', ['class' => 'button w-100 mt-15px']) ?>
        <?= Html::a('Войти', ['site/login'], ['class' => 'w-100 mt-15px text-center']) ?>

        <?php ActiveForm::end(); ?>
    </section>

</div>